### PR TITLE
libjobspec: Initial flux jobspec parser

### PR DESCRIPTION
**Pull request by morrone**
Introduce the first revision of the flux jobspec parser library.  It
is written in C++ and requires the C++ YAML parsing library name yaml-cpp.

The library is only built if yaml-cpp version 0.5.1 (or greater) is found.

Include a very rough debug tool called flux-jobspec-valdate.  It
will eventually grow into a full featured command line validation tool
for flux jobspec files and streams.

### CODE REVIEW

**Comment by morrone** [comment]
I haven't forgotten the other comments in pull request #1198.  But it looks like at least some versions of ubuntu do have libyaml-cpp, so I wanted to see what will happen if I run it through travis at this stage.

More updates still to come.

**Comment by grondo** [comment]
Looks like travis may still be missing part of boost?
```
In file included from /usr/include/yaml-cpp/node/node.h:10:0,
                 from /usr/include/yaml-cpp/yaml.h:13,
                 from ../../../../../src/common/libjobspec/jobspec.hpp:31,
                 from ../../../../../src/common/libjobspec/jobspec.cpp:25:
/usr/include/yaml-cpp/node/ptr.h:10:32: fatal error: boost/shared_ptr.hpp: No such file or directory
 #include <boost/shared_ptr.hpp>
```

This was just in the first build I looked at, I'll spot check the others as well.

**Comment by morrone** [comment]
Yes, thanks.  It looks like 0.5.1 needed it, and 0.5.2 and later no longer do.  I guess they failed to list that dependency in the package.  I'll add it to travis manually.

**Comment by grondo** [comment]
One travis failure due to #1169. I'll restart it.

**Comment by morrone** [comment]
Won't hurt, but I'm satisfied with the current travis status.  I'll have more pull request updates coming anyway.

**Comment by morrone** [comment]
Still a work in progress.  This update adds some testing.  Also some bug fixes.

The jobspec objects now also have stream insertion operators.

**Comment by dongahn** [comment]
Nice! 

BTW, just curious. I noticed that you replaced `AX_CXX_COMPILE_STDCXX` in `configure` with `CXXFLAGS = $(CXXFLAGS) -std=c++11` 

Didn't like how `AX_CXX_COMPILE_STDCXX` adds the  c++11 compliance option to the compiler command itself?

**Comment by morrone** [comment]
@dongahn , I think you are looking at an earlier revision of the branch.  On Monday I created pull request #1204, and this update (commit  5b9e54e) was rebased onto master after that landed.

**Comment by dongahn** [comment]
Indeed. Good to see you and I are using the same m4 as me for the C++ standard flag check. Plus, good to see `CODE_COVERAGE_CXXFLAGS` is also supported. It wasn't obvious. Thanks.

**Comment by morrone** [comment]
Assuming that this passes the tests again, it is ready for another round of reviews.  If there are no further changes needed from review, it is ready to land.

**Comment by garlick** [comment]
The single large commit should be split.  I'd suggest:

* build: find libyaml
* travis-ci: add libyaml to travis
* libjobspec: add initial jobspec parser
* cmd/flux-jobspec: add jobspec validator
* t/t0018-jobspec.t: test simple valid/invalid jobspec
* t/t0018-jobspec.t: test RFC 14 use cases

**Comment by garlick** [comment]
BTW what happened to the libflux/message change that you thought you needed before?

**Comment by morrone** [comment]
> BTW what happened to the libflux/message change that you thought you needed before?

You were right, it was actually misplaced in the commit; it should have been in the job-ingest commit.  Since I've dropped that part from the pull request, it doesn't appear here.

**Comment by morrone** [comment]
> The single large commit should be split. I'd suggest:

Suggest or require? :)

File: t/jobspec/valid/basic.yaml~ [hunk 1]
```diff
@@ -0,0 +1,19 @@
+version: 1
```
Comment (grondo) [inline t/jobspec/valid/basic.yaml~]: Is this backup file included by accident?

File: t/jobspec/valid/example1.yaml [hunk 2]
```diff
@@ -0,0 +1,19 @@
...
+          - type: core
+            count: 2
+tasks:
+  - command: app
+    slot: default
+    count:
+      per_slot: 1
+attributes:
+  system:
+    duration: 1 hour
```
Comment (grondo) [inline t/jobspec/valid/example1.yaml]: Github diff noted that this file is missing a final newline. Not a big deal if it works (or if it is on purpose), but I thought I'd point it out because it is different from all the other yaml files here.

**Comment by grondo** [comment]
Hm, a couple of my review comments got lost. They both involved the `flux jobspec-validate` command.

 * I like the idea and utility of a `flux jobspec` command. Was there some reason not to have `flux jobspec validate` instead of `flux jobspec-validate`? That would seem to make it easier to add future subcommands to the `flux jobspec` command.

 * My personal preference would be that `flux jobspec validate` prefix errors with the command name, but that is not a requirement. E.g. instead of `Unable to open file "invalid.yaml"` do `flux-jobspec-validate: Unable to open file "invalid.yaml"`.

**Comment by grondo** [comment]
> > The single large commit should be split. I'd suggest:

> Suggest or require? :)

I would also like to see the one large commit split. This is not only in the spirit of the [C4.1](https://github.com/flux-framework/rfc/blob/master/spec_1.adoc) requirement that "A patch SHOULD be a *minimal* and accurate answer to exactly one identified and agreed problem", but also I find it easier to track project history as well as handle merge conflicts when commits are built up in this logical way.

There are cases, though, where splitting a commit is especially onerous -- e.g. when it affects compilation of the project or causes ephemeral test failures that would thwart `git bisect`.

File: src/common/libjobspec/jobspec.hpp [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+/*
+ * This jobspec module handles parsing the Flux jobspec format as specified
+ * in Spec 14 in the Flux RFC project: https://github.com/flux-framework/rfc
+ *
+ * The primary interface in the library is the Flux:Jobspec::Jobspec class.
+ * The constructor Flux::Jobspec::Jobspec() can handle jobspec data in a
+ * std::string, std::istream, or the top document YAML::Node as pre-processed
+ * by the yaml-cpp library.
+ *
+ * When errors are found in the jobspec stream the library will raise the
```
Comment (dongahn) [inline src/common/libjobspec/jobspec.hpp]: Than you for the documentation for this!

File: src/common/libjobspec/jobspec.hpp [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+};
+
+enum class tristate_t { FALSE, TRUE, UNSPECIFIED };
+
+class Resource {
+public:
+    std::string type;
+    struct {
+        unsigned min;
+        unsigned max;
```
Comment (dongahn) [inline src/common/libjobspec/jobspec.hpp]: From the perspective of users of the jobspec library, it would be helpful to know what value the `max` field is going to be when only `min` is given. In this case, I would interpret that as "all available resources," but knowing what specific value I should test this condition on should be extremely helpful. Can this be documented somewhere? I don't believe this belongs to the spec itself but somewhere in this header file should suffice.

Comment (morrone) [reply src/common/libjobspec/jobspec.hpp]: One can't specify only min at this point.  That comment can be added when that change is made in the future.  First we need to change the rfc 14.

**Comment by morrone** [comment]
> "A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem", but also I find it easier to track project history as well as handle merge conflicts when commits are built up in this logical way.

I'm going to split it because it isn't worth fighting over, but here's how I see it: This one logical change.  It adds the parser and only parts directly connected to it.  The requested split is on file boundaries, so there is no clear benefit to review difficulty.  It also won't make any improvement to merge conflict complexity since it just splits at files rather than subsequent improvements, and separate logical changes that involve the same file. Further, there will now be commits with code that is unused and/or untested at points in the commit history.

When there are more clear incremental logical changes in a PR, for instance code refactoring following by a feature, it is completely worth while to make multiple commits.  But at each commit the PR should leave the tree in a reasonable state whenever possible.

File: t/jobspec/valid/basic.yaml~ (hunk 1 above)
Comment (morrone) [reply t/jobspec/valid/basic.yaml~]: Yes, thanks!

File: t/jobspec/valid/example1.yaml (hunk 2 above)
Comment (morrone) [reply t/jobspec/valid/example1.yaml]: I want to leave that one as-is.

**Comment by morrone** [comment]
> I like the idea and utility of a flux jobspec command. Was there some reason not to have flux jobspec validate instead of flux jobspec-validate? That would seem to make it easier to add future subcommands to the flux jobspec command.

Yes, I would like that eventually too.  I thought about creating a flux-jobspec command so that the "flux" command could accept "flux jobspec", and then flux-jobspec could further handle the next step, "flux jobspec validate".  But ultimately it seemed to make more sense to allow flux to handle multiple stages of spaces rather than just one.  The spelling of flux-jobspec-validate is designed to work with that enhancement in the future.

> My personal preference would be that flux jobspec validate prefix errors with the command name, but that is not a requirement. E.g. instead of Unable to open file "invalid.yaml" do flux-jobspec-validate: Unable to open file "invalid.yaml".

That is fine with me.

**Comment by garlick** [comment]
> But ultimately it seemed to make more sense to allow the "flux" command to handle multiple stages of spaces rather than just one. The spelling of flux-jobspec-validate is designed to work with that enhancement in the future.

That's not how our commands work in general, so very likely when you propose `flux-jobspec-foo`, you will get a review comment to consolidate the jobspec sub-commands.

In fact, does this validator need to be installed as a user-facing command?  Perhaps it is more appropriate as a test driver under `t/jobspec`.

> I'm going to split it because it isn't worth fighting over

You make some reasonable points, but It's actually easier to review in smaller, topical chunks (not taken to the extreme of course), and now your focused commit comments make for a better history.  For example it's now clear based on the history which test input should be kept in sync with RFC 14 and which could be modified to improve coverage or whatever.

**Comment by morrone** [comment]
> In fact, does this validator need to be installed as a user-facing command? Perhaps it is more appropriate as a test driver under t/jobspec.

Yes, it is meant to be the start of a user-facing command.  This will give users an easy way to check their jobspecs during development without having to submit them.  Other commands I foresee are "flux jobspec submit" and "flux jobspec simulate".

The simulator would attempt to simulate what is going to happen when the jobspec is executed by flux.  I'm not entirely clear on how much detail that could give, or quite how to even express that information yet. :)  That idea came from a discussion with Ben, so maybe he'll have some ideas for us.  It might be a post-S4 item too.

**Comment by grondo** [comment]
> The simulator would attempt to simulate what is going to happen when the jobspec is executed by flux. I'm not entirely clear on how much detail that could give, or quite how to even express that information yet. :) That idea came from a discussion with Ben, so maybe he'll have some ideas for us. It might be a post-S4 item too.

That is a great idea!

**Comment by garlick** [comment]
Cool, so sounds like we need `flux-jobspec-validate` renamed to `flux-jobspec` with one subcommand (for extra credit set up optparse structure for subcommands), and the output mods suggested by @grondo, and then this is good to go?  I'm signing off for a while and I'm fine with whatever you and @grondo work out.  Nice work.

**Comment by dongahn** [comment]
This works for me.

**Comment by morrone** [comment]
> Cool, so sounds like we need flux-jobspec-validate renamed to flux-jobspec with one subcommand (for extra credit set up optparse structure for subcommands), and the output mods suggested by @grondo, and then this is good to go?

This already addresses everything @grondo asked for, I believe.  I plan to leave the command as "flux jobspec-validate" for now.

**Comment by grondo** [comment]
> The flux-jobspec or enhanhment to the flux command can be added later without needing to touch the flux-jobspec-validate program.

Fine to leave as flux-jobspec-validate for now I think, since there aren't any other jobspec commands yet there's no reason to hide it behind a parent command so far.

However, I'm a bit worried about the future "enhancement to the flux command" -- you're not talking about directly adding jobspec support to the flux(1) command?

**Comment by garlick** [comment]
I'm confused by the last couple comments.  Are we in agreement that when further subcommands are added, this command will be renamed to `flux-jobspec` with a `validate` subcommand?

I'm OK with merging as is to get the capability integrated as long as we open a bug to rename the command.  However, I'm not sure why we wouldn't just rename it now before references appear (say in test scripts) that we will have to change later.

**Comment by morrone** [comment]
> I'm confused by the last couple comments. Are we in agreement that when further subcommands are added, this command will be renamed to flux-jobspec with a validate subcommand?

No, I think it will still be named flux-jobspec-validate.  There may be an intermediate command named flux-jobspec that calls it, or the "flux" command itself might be enhanced to handle multiple levels of "-" in subcommands.  It is not clear that renaming flux-jobspec-validate will ever be the way to go.

**Comment by garlick** [comment]
You are presuming a change to the way flux commands work that hasn't been proposed or discussed, but this is an important PR that shouldn't be held up while we go off on a tangent, IMHO.

Open bug on naming issue and rebase?

**Comment by grondo** [comment]
> No, I think it will still be named flux-jobspec-validate. There may be an intermediate command named flux-jobspec that calls it, or the "flux" command itself might be enhanced to handle multiple levels of "-" in subcommands. It is not clear that renaming flux-jobspec-validate will ever be the way to go.

Not sure if you're being purposely mysterious, but if we made `flux` able to handle multiple levels of `-` in subcommands you break existing commands that have a `-` but aren't subcommands, so we can probably take that off the table.

I guess it still isn't clear why the jobspec commands are special and can't be handled like all the other existing flux commands. Since you're proposing a change to existing practice, you unfortunately have an implied burden to prove your approach warrants the change.

**Comment by grondo** [comment]
> ut this is an important PR that shouldn't be held up while we go off on a tangent, IMHO.

> Open bug on naming issue and rebase?

Sorry, missed your comment @garlick.

I agree.

**Comment by morrone** [comment]
> Not sure if you're being purposely mysterious, but if we made flux able to handle multiple levels of - in subcommands you break existing commands that have a - but aren't subcommands, so we can probably take that off the table.

I'm confused about what part of what I'm saying seems mysterious.  Can you point me at a current command that has multiple levels of - and would be broken by what I suggest?  There aren't any obvious commands like that in src/cmd or src/cmd/builtins, so that comment is kind of mysterious. :)

> I guess it still isn't clear why the jobspec commands are special and can't be handled like all the other existing flux commands. Since you're proposing a change to existing practice, you unfortunately have an implied burden to prove your approach warrants the change.

I don't believe that I was the person to introduce that external consideration into this PR. :)  But yes, I'm happy to start a separate issue if that lets this PR land.

**Comment by grondo** [comment]
> Can you point me at a current command that has multiple levels of - and would be broken by what I suggest? 

Oops, sorry, I was thinking of `flux comms-stats` which has since been renamed. I also used `flux mock-imp` as a command in the IMP prototype. But, you're correct nothing would currently break, sorry! (It would be nice not to close the door on future commands with `-` embedded, though)

I guess the mystery is *why* you are proposing that the current method for adding subcommands isn't sufficient for your use case, and a new method is required.

**Comment by grondo** [comment]
> I don't believe that I was the person to introduce that external consideration into this PR. :) 

Ha, point taken! :-)

I think that suggestion had come when there were two `jobspec-` prefixed subcommands, `jobspec-validate` and `jobspec-submit`.

**Comment by morrone** [comment]
Issue #1226 discusses possible sub-sub-commands.

**Comment by grondo** [comment]
Ok. Just needs a rebase on latest master and ready for merge
