### ISSUE TITLE
enabling caliper

### ISSUE THREAD

**Issue by JaeseungYeom** [flux-framework/flux-core#3112]
I am trying to build flux with caliper. I configure flux  as
```PKG_CONFIG_PATH=caliper_install_path/lib64/pkgconfig:${PKG_CONFIG_PATH} ./configure --prefix=flux_install_path --enable-caliper=yes```

Then, I am getting the compilation error as below

handle.c:184:25: error: passing argument 4 of 'cali_push_snapshot' from incompatible pointer type [-Werror]
                         data /* event_data */

**Comment by grondo** [comment]
Hm, we may need to update flux-core to work with the latest versions of Caliper -- I don't believe we've updated in quite awhile. Our docker images which we use for build/test are tied to Caliper version 1.7.0. To make progress you may want to try building and installing that version of Caliper if possible.

What version of Caliper are you using?

**Comment by JaeseungYeom** [comment]
I just use the one I pulled from the repo. It seems to be 2.5.0-dev. I will try 1.7.0.

**Comment by grondo** [comment]
If that doesn't work for you I will see how much effort it will be to update to 2.5.

**Comment by dongahn** [comment]
@JaeseungYeom: if this requires too much effort, we should also chat whether we can use other methods to measure the performance you want to measure. It is not super clear if Caliper will give you the critical path info you need anyway.

**Comment by JaeseungYeom** [comment]
I was able to build with 1.8.0, which is currently the oldest version available from the repo. Thanks.
