### ISSUE TITLE
Docker build issue with new merge for ubuntu container

### ISSUE THREAD

**Issue by vsoch** [flux-framework/flux-core#4962]
See https://github.com/flux-framework/flux-core/actions/runs/4271415071/jobs/7435869316.

I'm working on the flux operator now but I'll make time to look at this after that.

**Comment by vsoch** [comment]
okay here is some insight! First I installed ply (`pip install ply`) because that was missing. Now it's failing with something related to lua:

```
#0 33.93 /usr/bin/ld: warning: libflux-idset.so.1, needed by ../../src/common/.libs/libflux-taskmap.so, not found (try using -rpath or -rpath-link)
#0 33.99 /usr/bin/ld: ../../src/bindings/lua/.libs/libfluxlua.a(lutil.o): in function `l_format_args':
#0 33.99 /workspaces/core/src/bindings/lua/lutil.c:67: undefined reference to `lua_replace'
#0 34.00 /usr/bin/ld: .libs/flux-shell: local symbol `idset_destroy' in ../../src/common/.libs/libflux-internal.a(libidset_la-idset.o) is referenced by DSO
#0 34.00 /usr/bin/ld: final link failed: bad value
#0 34.00 collect2: error: ld returned 1 exit status
#0 34.00 make[2]: *** [Makefile:1187: flux-shell] Error 1
#0 34.00 make[2]: Leaving directory '/code/src/shell'
#0 34.00 make[1]: *** [Makefile:516: all-recursive] Error 1
#0 34.00 make[1]: Leaving directory '/code/src'
#0 34.00 make: *** [Makefile:592: all-recursive] Error 1
------
````
This is also after I updated lua from 5.1 to 5.3 (still got an error about missing symbols, etc.). Is there a flag that needs to be added to configure or similar?

**Comment by grondo** [comment]
@vsoch, can I ask what the use case for this extra ubuntu container is? I was able to build it just fine with the addition of `python3-ply` _package_, but there are other issues with the container like it reports the wrong flux-core version.

We do already have a 22.04 ubuntu container built in CI, so I'm wondering if we actually require this second container, since that means we have multiple places to keep dependencies up to date, etc.

**Comment by vsoch** [comment]
I’d be ok to remove it - the issue with the others is that it’s non trivial for someone to figure out how to build their own recipe from scratch.

**Comment by grondo** [comment]
> the issue with the others is that it’s non trivial for someone to figure out how to build their own recipe from scratch.

Sounds like a reasonable complaint, though I'm not sure what a recipe is in this context. Sorry! :slightly_frowning_face:

**Comment by vsoch** [comment]
Recipe == Dockerfile. It’s usually good to have an obvious one someone can grab and build.

**Comment by vsoch** [comment]
As an example, here is a franken Dockerfile I put together earlier this week (and it took me most of an evening session to figure it out from different repos):

```dockerfile
FROM ubuntu:bionic

# docker build -t vanessa/flux-core:janky .

# This first section from src/test/docker/bionic/Dockerfile in flux-core
# https://github.com/flux-framework/flux-core/blob/master/src/test/docker/bionic/Dockerfile
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        apt-utils && \
    rm -rf /var/lib/apt/lists/*

# Utilities
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        locales \
        ca-certificates \
        wget \
        man \
        git \
        flex \
        ssh \
        sudo \
        vim \
        luarocks \
        munge \
        lcov \
        ccache \
        lua5.2 \
        mpich \
        valgrind \
        jq && \
    rm -rf /var/lib/apt/lists/*

# Compilers, autotools
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        build-essential \
        pkg-config \
        autotools-dev \
        libtool \
        autoconf \
        automake \
        make \
        cmake \
        clang-6.0 \
        clang-tidy \
        gcc-8 \
        g++-8 && \
    rm -rf /var/lib/apt/lists/*

# Python
# NOTE: sudo pip install is necessary to get differentiated installations of
# python binary components for multiple python3 variants, --ignore-installed
# makes it ignore local versions of the packages if your home directory is
# mapped into the container and contains the same libraries
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
	libffi-dev \
        python3-dev \
        python3.7-dev \
        python3.8-dev \
        python3-pip \
        python3-setuptools \
        python3-wheel && \
    rm -rf /var/lib/apt/lists/*

RUN for PY in python3.6 python3.7 python3.8 ; do \
        sudo $PY -m pip install --upgrade --ignore-installed \
	    "markupsafe==2.0.0" \
            coverage cffi ply six pyyaml "jsonschema>=2.6,<4.0" \
            sphinx sphinx-rtd-theme sphinxcontrib-spelling; \
	sudo mkdir -p /usr/lib/${PY}/dist-packages; \
	echo ../site-packages >/tmp/site-packages.pth; \
	sudo mv /tmp/site-packages.pth /usr/lib/${PY}/dist-packages; \
    done ; \
    apt-get -qq purge -y python3-pip && \
    apt-get -qq autoremove -y

# Other deps
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        libsodium-dev \
        libzmq3-dev \
        libczmq-dev \
        libjansson-dev \
        libmunge-dev \
        libncursesw5-dev \
        liblua5.2-dev \
        liblz4-dev \
        libsqlite3-dev \
        uuid-dev \
        libhwloc-dev \
        libmpich-dev \
        libs3-dev \
        libevent-dev \
        libarchive-dev \
        libpam-dev && \
    rm -rf /var/lib/apt/lists/*

# Testing utils and libs
RUN apt-get update && \
    apt-get -qq install -y --no-install-recommends \
        faketime \
        libfaketime \
        pylint \
        cppcheck \
        enchant \
        aspell \
        aspell-en && \
    rm -rf /var/lib/apt/lists/*

RUN locale-gen en_US.UTF-8

# NOTE: luaposix installed by rocks due to Ubuntu bug: #1752082 https://bugs.launchpad.net/ubuntu/+source/lua-posix/+bug/1752082
RUN luarocks install luaposix

# Install caliper by hand for now
WORKDIR /opt/caliper
RUN wget -O - https://github.com/LLNL/Caliper/archive/v1.7.0.tar.gz | tar xvz --strip-components 1 && \
    mkdir build && \
    cd build && \
    CC=gcc CXX=g++ cmake .. -DCMAKE_INSTALL_PREFIX=/usr && \
    make -j 4 && \
    make install && \
    cd ../.. && \
    rm -rf caliper

# Install openpmix, prrte
WORKDIR /opt/prrte
RUN git clone https://github.com/openpmix/openpmix.git && \
    git clone https://github.com/openpmix/prrte.git && \
    ls -l && \
    set -x && \
    cd openpmix && \
    git checkout fefaed568f33bf86f28afb6e45237f1ec5e4de93 && \
    ./autogen.pl && \
    ./configure --prefix=/usr --disable-static && make -j 4 install && \
    ldconfig && \
    cd .. && \
    cd prrte && \
    git checkout 477894f4720d822b15cab56eee7665107832921c && \
    ./autogen.pl && \
    ./configure --prefix=/usr && make -j 4 install && \
    cd ../.. && \
    rm -rf prrte

ENV LANG=C.UTF-8

# This is from the docker check script (run interactively during a test)
# https://github.com/flux-framework/flux-core/blob/master/src/test/docker/checks/Dockerfile
ARG USER=fluxuser
ARG UID=1000
ARG GID=1000
ARG FLUX_SECURITY_VERSION=0.8.0

# Install flux-security by hand for now:
#
WORKDIR /opt
RUN CCACHE_DISABLE=1 && \
    V=$FLUX_SECURITY_VERSION && \
    PKG=flux-security-$V && \
    URL=https://github.com/flux-framework/flux-security/releases/download && \
    wget ${URL}/v${V}/${PKG}.tar.gz && \
    tar xvfz ${PKG}.tar.gz && \
    cd ${PKG} && \
    ./configure --prefix=/usr --sysconfdir=/etc || cat config.log && \
    make -j 4 && \
    make install && \
    cd .. && \
    rm -rf flux-security-*


# Add configured user to image with sudo access:
#
RUN set -x && groupadd -g $UID $USER && \
    useradd -g $USER -u $UID -d /home/$USER -m $USER && \
    printf "$USER ALL= NOPASSWD: ALL\\n" >> /etc/sudoers

# Setup MUNGE directories & key
RUN mkdir -p /var/run/munge && \
    dd if=/dev/urandom bs=1 count=1024 > /etc/munge/munge.key && \
    chown -R munge /etc/munge/munge.key /var/run/munge && \
    chmod 600 /etc/munge/munge.key

# Build flux core
# This I added and copied how to build with caliper / flux security enabled
# https://github.com/flux-framework/flux-core/blob/master/src/test/docker/docker-run-checks.sh#L185-L191
RUN git clone --depth 1 -b disable-sign-id-check https://github.com/researchapps/flux-core && \
    cd flux-core && \
    ./autogen.sh && \
    ./configure --prefix=/usr --sysconfdir=/etc \
        --with-systemdsystemunitdir=/etc/systemd/system \
        --localstatedir=/var \
        --with-flux-security \
        --enable-caliper && \
    make clean && \
    make && \
    sudo make install

# This is from the same src/test/docker/bionic/Dockerfile but in flux-sched
# Flux-sched deps
RUN sudo apt-get update
RUN sudo apt-get -qq install -y --no-install-recommends \
	libboost-graph-dev \
	libboost-system-dev \
	libboost-filesystem-dev \
	libboost-regex-dev \
	python-yaml \
	libyaml-cpp-dev \
	libedit-dev

# Build Flux Sched	
# https://github.com/flux-framework/flux-sched/blob/master/src/test/docker/docker-run-checks.sh#L152-L158
RUN git clone --depth 1 https://github.com/flux-framework/flux-sched && \
    cd flux-sched && \
    ./autogen.sh && \
    ./configure --prefix=/usr --sysconfdir=/etc \
       --with-systemdsystemunitdir=/etc/systemd/system \
       --localstatedir=/var \
       --with-flux-security \
       --enable-caliper && \
    make && \
    sudo make install

# Note I ran this manually - didn't check to see if works in build (4th line might be interactive
RUN sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 1 && \
    sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 2 && \
    sudo update-alternatives --config python3 && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py

WORKDIR /opt/flux-core
```
Whatever solution we have, we need to provide a "jump in and get started" template that an interested developer user can customize. I had added the ubuntu one as a logical base, and I figured people would want one with spack too.

**Comment by grondo** [comment]
> here is a franken Dockerfile I put together earlier this week (and it took me most of an evening session to figure it out from different repos

What are you trying to do with that? In this case would `docker run -ti fluxrm/flux-sched` have worked? If you need to customize, then can you start with

```
FROM fluxrm/flux-sched:latest
```
or 
```
FROM fluxrm/flux-core:latest
```
as needed.

However, I see what you are saying if someone wants to start from scratch for some reason. Maybe we can just update the base ubuntu container to use `scripts/install-deps-deb.sh` which is referenced from the `README.md` so that we reduce the number of lists of dependencies.

**Comment by vsoch** [comment]
Oh gosh I think... I was trying to do a custom build for flux core? And I needed flux security. I definitely wouldn't have gone done that path if using flux-sched would have worked - I do normally use that for everything!  :laughing:

**Comment by vsoch** [comment]
@grondo can we just delete these? https://github.com/flux-framework/flux-core/tree/master/etc/docker/spack I don't think they are actively building or being used, and I certainly have a gazillion dockerfile derivatives elsewhere.

**Comment by grondo** [comment]
Fine with me! Thanks!

**Comment by grondo** [comment]
Hm, looking [here](https://github.com/flux-framework/flux-core/pkgs/container/flux-spack-base/158835397), there are 3 downloads of the (second to most recent) build. Should we still go ahead and remove?

**Comment by vsoch** [comment]
We can't be sure, but typically registries have a few downloads (that are automated) for scanning. It's up to you. My sense would be we'd be better off moving those out of the repository here (and putting them somewhere else) so if a user reports an issue "Where did my image go?" we can direct them there. What do you think, and if you like that idea, should we make a repository just for them?

If they aren't bothering anyone and you don't mind the extra stuff, then I suppose we can just leave. And I'm good to close this issue.

**Comment by grondo** [comment]
If there are no known users, let's just remove it for now and add the separate repo as needed.

**Comment by vsoch** [comment]
See https://github.com/flux-framework/flux-core/pull/5628. I will put the builds elsewhere, so they are ready to go if/when someone wants/needs them.
